#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from kompilator.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "kompilator.y"

#include "functions.h"
stack<unsigned long long int> st;
stack<unsigned long long int> reg_stack;
stack<ParserVar> for_stack;

#line 8 "kompilator.y"
typedef union {
	char *str;
	unsigned long long int num;
	ParserVar var;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	EQUAL	258
#define	ADD	259
#define	MINUS	260
#define	MULTI	261
#define	DIV	262
#define	MODULO	263
#define	LEFT	264
#define	RIGHT	265
#define	LESS	266
#define	LESS_OR_EQUAL	267
#define	MORE	268
#define	MORE_OR_EQUAL	269
#define	DIFFERENT	270
#define	SEMICOLON	271
#define	ASSIGN	272
#define	DECLARE	273
#define	IN	274
#define	GET	275
#define	PUT	276
#define	IF	277
#define	THEN	278
#define	ELSE	279
#define	ENDIF	280
#define	WHILE	281
#define	DO	282
#define	ENDWHILE	283
#define	FOR	284
#define	DOWN	285
#define	FROM	286
#define	TO	287
#define	ENDFOR	288
#define	END	289
#define	ID	290
#define	NUM	291


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int EQUAL;
static const int ADD;
static const int MINUS;
static const int MULTI;
static const int DIV;
static const int MODULO;
static const int LEFT;
static const int RIGHT;
static const int LESS;
static const int LESS_OR_EQUAL;
static const int MORE;
static const int MORE_OR_EQUAL;
static const int DIFFERENT;
static const int SEMICOLON;
static const int ASSIGN;
static const int DECLARE;
static const int IN;
static const int GET;
static const int PUT;
static const int IF;
static const int THEN;
static const int ELSE;
static const int ENDIF;
static const int WHILE;
static const int DO;
static const int ENDWHILE;
static const int FOR;
static const int DOWN;
static const int FROM;
static const int TO;
static const int ENDFOR;
static const int END;
static const int ID;
static const int NUM;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,EQUAL=258
	,ADD=259
	,MINUS=260
	,MULTI=261
	,DIV=262
	,MODULO=263
	,LEFT=264
	,RIGHT=265
	,LESS=266
	,LESS_OR_EQUAL=267
	,MORE=268
	,MORE_OR_EQUAL=269
	,DIFFERENT=270
	,SEMICOLON=271
	,ASSIGN=272
	,DECLARE=273
	,IN=274
	,GET=275
	,PUT=276
	,IF=277
	,THEN=278
	,ELSE=279
	,ENDIF=280
	,WHILE=281
	,DO=282
	,ENDWHILE=283
	,FOR=284
	,DOWN=285
	,FROM=286
	,TO=287
	,ENDFOR=288
	,END=289
	,ID=290
	,NUM=291


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::EQUAL=258;
const int YY_parse_CLASS::ADD=259;
const int YY_parse_CLASS::MINUS=260;
const int YY_parse_CLASS::MULTI=261;
const int YY_parse_CLASS::DIV=262;
const int YY_parse_CLASS::MODULO=263;
const int YY_parse_CLASS::LEFT=264;
const int YY_parse_CLASS::RIGHT=265;
const int YY_parse_CLASS::LESS=266;
const int YY_parse_CLASS::LESS_OR_EQUAL=267;
const int YY_parse_CLASS::MORE=268;
const int YY_parse_CLASS::MORE_OR_EQUAL=269;
const int YY_parse_CLASS::DIFFERENT=270;
const int YY_parse_CLASS::SEMICOLON=271;
const int YY_parse_CLASS::ASSIGN=272;
const int YY_parse_CLASS::DECLARE=273;
const int YY_parse_CLASS::IN=274;
const int YY_parse_CLASS::GET=275;
const int YY_parse_CLASS::PUT=276;
const int YY_parse_CLASS::IF=277;
const int YY_parse_CLASS::THEN=278;
const int YY_parse_CLASS::ELSE=279;
const int YY_parse_CLASS::ENDIF=280;
const int YY_parse_CLASS::WHILE=281;
const int YY_parse_CLASS::DO=282;
const int YY_parse_CLASS::ENDWHILE=283;
const int YY_parse_CLASS::FOR=284;
const int YY_parse_CLASS::DOWN=285;
const int YY_parse_CLASS::FROM=286;
const int YY_parse_CLASS::TO=287;
const int YY_parse_CLASS::ENDFOR=288;
const int YY_parse_CLASS::END=289;
const int YY_parse_CLASS::ID=290;
const int YY_parse_CLASS::NUM=291;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		91
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 291 ? yytranslate[x] : 50)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,     9,    15,    16,    19,    20,    25,    31,    39,
    45,    46,    57,    58,    70,    74,    78,    80,    82,    86,
    90,    94,    98,   102,   106,   110,   114,   118,   122,   126,
   128,   130,   132,   134,   136,   138,   143
};

static const short yyrhs[] = {    18,
    38,    19,    39,    34,     0,    38,    35,     0,    38,    35,
     9,    36,    10,     0,     0,    39,    40,     0,     0,    49,
    17,    44,    16,     0,    22,    45,    23,    39,    25,     0,
    22,    45,    23,    39,    43,    39,    25,     0,    26,    45,
    27,    39,    28,     0,     0,    29,    46,    31,    47,    32,
    48,    41,    27,    39,    33,     0,     0,    29,    46,    30,
    31,    47,    32,    48,    42,    27,    39,    33,     0,    20,
    49,    16,     0,    21,    47,    16,     0,    24,     0,    47,
     0,    47,     4,    47,     0,    47,     5,    47,     0,    47,
     6,    47,     0,    47,     7,    47,     0,    47,     8,    47,
     0,    47,     3,    47,     0,    47,    15,    47,     0,    47,
    11,    47,     0,    47,    13,    47,     0,    47,    12,    47,
     0,    47,    14,    47,     0,    35,     0,    49,     0,    36,
     0,    49,     0,    36,     0,    35,     0,    35,     9,    36,
    10,     0,    35,     9,    35,    10,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    58,    63,    67,    71,    76,    77,    82,    91,    95,    99,
   105,   119,   129,   145,   158,   170,   179,   188,   195,   208,
   221,   243,   261,   294,   311,   328,   341,   354,   367,   384,
   394,   395,   411,   412,   422,   435,   446
};

static const char * const yytname[] = {   "$","error","$illegal.","EQUAL","ADD",
"MINUS","MULTI","DIV","MODULO","LEFT","RIGHT","LESS","LESS_OR_EQUAL","MORE",
"MORE_OR_EQUAL","DIFFERENT","SEMICOLON","ASSIGN","DECLARE","IN","GET","PUT",
"IF","THEN","ELSE","ENDIF","WHILE","DO","ENDWHILE","FOR","DOWN","FROM","TO",
"ENDFOR","END","ID","NUM","program","vdeclarations","commands","command","@1",
"@2","else","expression","condition","iterator","value","factor","identifier",
""
};
#endif

static const short yyr1[] = {     0,
    37,    38,    38,    38,    39,    39,    40,    40,    40,    40,
    41,    40,    42,    40,    40,    40,    43,    44,    44,    44,
    44,    44,    44,    45,    45,    45,    45,    45,    45,    46,
    47,    47,    48,    48,    49,    49,    49
};

static const short yyr2[] = {     0,
     5,     2,     5,     0,     2,     0,     4,     5,     7,     5,
     0,    10,     0,    11,     3,     3,     1,     1,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     1,
     1,     1,     1,     1,     1,     4,     4
};

static const short yydefact[] = {     0,
     4,     0,     6,     2,     0,     0,     0,     0,     0,     0,
     0,     1,    35,     5,     0,     0,     0,    32,     0,    31,
     0,     0,     0,    30,     0,     0,     0,     3,    15,    16,
     6,     0,     0,     0,     0,     0,     0,     6,     0,     0,
     0,     0,     0,    18,     0,    24,    26,    28,    27,    29,
    25,     0,     0,     0,    37,    36,     7,     0,     0,     0,
     0,     0,    17,     8,     6,    10,     0,     0,    19,    20,
    21,    22,    23,     0,     0,    34,    11,    33,     9,    13,
     0,     0,     6,     6,     0,     0,    12,    14,     0,     0,
     0
};

static const short yydefgoto[] = {    89,
     2,     5,    14,    81,    82,    65,    43,    21,    25,    22,
    77,    20
};

static const short yypact[] = {   -11,
-32768,   -16,-32768,     9,    15,    -2,     4,   -30,   -30,   -30,
     7,-32768,    34,-32768,    28,    14,    32,-32768,    45,-32768,
    39,   102,    41,-32768,   -15,   -14,   -30,-32768,-32768,-32768,
-32768,   -30,   -30,   -30,   -30,   -30,   -30,-32768,    40,   -30,
    55,    62,    58,   114,   -12,-32768,-32768,-32768,-32768,-32768,
-32768,    38,   -30,    43,-32768,-32768,-32768,   -30,   -30,   -30,
   -30,   -30,-32768,-32768,-32768,-32768,    44,    -4,-32768,-32768,
-32768,-32768,-32768,    57,    -4,-32768,-32768,-32768,-32768,-32768,
    63,    64,-32768,-32768,    67,    77,-32768,-32768,    84,    85,
-32768
};

static const short yypgoto[] = {-32768,
-32768,   -27,-32768,-32768,-32768,-32768,-32768,    91,-32768,    -7,
    19,    -5
};


#define	YYLAST		122


static const short yytable[] = {    15,
    19,    17,     3,    45,    13,    18,     1,     7,     8,     9,
    52,    63,    64,    10,    39,    40,    11,     6,     4,    44,
    41,    42,    13,    28,    46,    47,    48,    49,    50,    51,
    13,    76,    54,    16,     7,     8,     9,    74,    13,    15,
    10,    24,    26,    11,    27,    67,    15,    29,    12,    13,
    69,    70,    71,    72,    73,    85,    86,     7,     8,     9,
    30,    31,    78,    10,    55,    66,    11,    38,    15,    78,
    53,    56,    13,    57,    68,    75,     7,     8,     9,    15,
    15,    79,    10,    90,    91,    11,     7,     8,     9,    83,
    84,    13,    10,    80,     0,    11,     7,     8,     9,    87,
    23,    13,    10,     0,    32,    11,     0,     0,     0,    88,
     0,    13,    33,    34,    35,    36,    37,    58,    59,    60,
    61,    62
};

static const short yycheck[] = {     5,
     8,     7,    19,    31,    35,    36,    18,    20,    21,    22,
    38,    24,    25,    26,    30,    31,    29,     9,    35,    27,
    35,    36,    35,    10,    32,    33,    34,    35,    36,    37,
    35,    36,    40,    36,    20,    21,    22,    65,    35,    45,
    26,    35,     9,    29,    17,    53,    52,    16,    34,    35,
    58,    59,    60,    61,    62,    83,    84,    20,    21,    22,
    16,    23,    68,    26,    10,    28,    29,    27,    74,    75,
    31,    10,    35,    16,    32,    32,    20,    21,    22,    85,
    86,    25,    26,     0,     0,    29,    20,    21,    22,    27,
    27,    35,    26,    75,    -1,    29,    20,    21,    22,    33,
    10,    35,    26,    -1,     3,    29,    -1,    -1,    -1,    33,
    -1,    35,    11,    12,    13,    14,    15,     4,     5,     6,
     7,     8
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 58 "kompilator.y"
{ addOutput("HALT"); printOutput(); ;
    break;}
case 2:
#line 63 "kompilator.y"
{
	if (isDeclared(yyvsp[0].str, false)) yyerror("Redeclaration of variable "+string(yyvsp[0].str));
	else declareVariable(yyvsp[0].str, -1);
;
    break;}
case 3:
#line 67 "kompilator.y"
{
	if (isDeclared(yyvsp[-3].str, true)) yyerror("Redeclaration of array "+string(yyvsp[-3].str));
	else declareVariable(yyvsp[-3].str, yyvsp[-1].num);
;
    break;}
case 4:
#line 71 "kompilator.y"
{ initRegisters(); ;
    break;}
case 7:
#line 82 "kompilator.y"
{
	if (!isIterator(yyvsp[-3].var.name)) {
		if (isRegister(yyvsp[-1].var.stored)) {
			if (!yyvsp[-1].var.error) {
				storeVariable(yyvsp[-3].var, yyvsp[-1].var);
			} else yyerror("Trying to access uninitialized variable");
		} else yyerror("Result of expression isn't stored in register");
	} else yyerror("Trying change iterator value");
;
    break;}
case 8:
#line 91 "kompilator.y"
{
	setOutput(st.top(), intToString(getK())); st.pop(); st.pop();
	resetAllRegisters(true);
;
    break;}
case 9:
#line 95 "kompilator.y"
{
	setOutput(st.top(), intToString(getK())); st.pop(); st.pop();
	resetAllRegisters(true);
;
    break;}
case 10:
#line 99 "kompilator.y"
{
	resetAllRegisters(false);
	setOutput(st.top(), intToString(getK()+1)); st.pop();
	addOutput("JUMP "+intToString(st.top())); st.pop();
	resetAllRegisters(true);
;
    break;}
case 11:
#line 105 "kompilator.y"
{
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	storeIterator(yyvsp[-4].var, reg_1);
	st.push(getK());
	reg_1 = prepareRegister(yyvsp[-4].var);  	setRegister(reg_1, true);
	Register reg_2 = prepareRegister(yyvsp[0].var);  	setRegister(reg_2, true);
	addOutput("INC "+intToString(reg_2.index));
	addOutput("SUB "+intToString(reg_2.index)+" "+intToString(reg_1.index));
	freeRegister(reg_1.index, true);
	for_stack.push(yyvsp[-4].var);	 st.push(getK());
	addOutput("JZERO "+intToString(reg_2.index)+" ");
	freeRegister(reg_2.index, true);
	reg_stack.push(reg_2.index);
;
    break;}
case 12:
#line 119 "kompilator.y"
{
	ParserVar p1 = for_stack.top();	for_stack.pop();
	Register reg = prepareRegister(p1);
	addOutput("INC "+intToString(reg.index));
	storeIterator(p1, reg);
	setOutput(st.top(), intToString(getK()+1)); st.pop();
	addOutput("JUMP "+intToString(st.top())); st.pop();
	deleteIterator(p1);
	freeRegister(reg_stack.top(), true); reg_stack.pop();
;
    break;}
case 13:
#line 129 "kompilator.y"
{
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	storeIterator(yyvsp[-5].var, reg_1);
	st.push(getK());
	reg_1 = prepareRegister(yyvsp[-5].var);
	setRegister(reg_1, true);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	setRegister(reg_2, true);
	addOutput("INC "+intToString(reg_1.index));
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	for_stack.push(yyvsp[-5].var);	 st.push(getK());
	addOutput("JZERO "+intToString(reg_1.index)+" ");
	freeRegister(reg_1.index, true);
	reg_stack.push(reg_1.index);
;
    break;}
case 14:
#line 145 "kompilator.y"
{
	ParserVar p1 = for_stack.top();	for_stack.pop();
	Register reg = prepareRegister(p1);
	unsigned long long int index = getK();
	addOutput("JZERO "+intToString(reg.index)+" ");
	addOutput("DEC "+intToString(reg.index));
	storeIterator(p1, reg);
	setOutput(st.top(), intToString(getK()+1)); st.pop();
	addOutput("JUMP "+intToString(st.top())); st.pop();
	setOutput(index, intToString(getK()));
	deleteIterator(p1);
	freeRegister(reg_stack.top(), true); reg_stack.pop();
;
    break;}
case 15:
#line 158 "kompilator.y"
{
	Register reg = getFreeRegister();
	addOutput("READ "+intToString(reg.index));
	Register reg_2 = getFreeRegister();
	setValueInRegister(yyvsp[-1].var.stored - 10, reg_2.index);
	addOutput("STORE "+intToString(reg.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	freeRegister(reg.index, true);
	Variable v = getVariable(yyvsp[-1].var.name);
	v.value = 0;
	setVariable(v);
;
    break;}
case 16:
#line 170 "kompilator.y"
{
	Register reg = prepareRegister(yyvsp[-1].var);
	addOutput("WRITE "+intToString(reg.index));
	freeRegister(reg.index, true);
;
    break;}
case 17:
#line 179 "kompilator.y"
{
	setOutput(st.top(), intToString(getK()+1));
	st.pop(); st.push(getK());
	addOutput("JUMP ");
;
    break;}
case 18:
#line 188 "kompilator.y"
{
	Register reg = prepareRegister(yyvsp[0].var);
	yyval.var.index = -1;
	yyval.var.stored = reg.index;
	yyval.var.value = yyvsp[0].var.value;
	if (yyvsp[0].var.value == -1) yyval.var.error = true;
;
    break;}
case 19:
#line 195 "kompilator.y"
{
	int quickResult = quickAddition(yyvsp[-2].var, yyvsp[0].var);
	if (quickResult != -1) yyval.var.stored = quickResult;
	else {
		Register reg_1 = prepareRegister(yyvsp[-2].var);
		Register reg_2 = prepareRegister(yyvsp[0].var);
		addOutput("ADD "+intToString(reg_1.index)+" "+intToString(reg_2.index));
		freeRegister(reg_2.index, true);
		yyval.var.stored = reg_1.index;
	}
	yyval.var.index = -1;
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 20:
#line 208 "kompilator.y"
{
	int quickResult = quickSubtraction(yyvsp[-2].var, yyvsp[0].var);
	if (quickResult != -1) yyval.var.stored = quickResult;
	else {
		Register reg_1 = prepareRegister(yyvsp[-2].var);
		Register reg_2 = prepareRegister(yyvsp[0].var);
		addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_2.index));
		freeRegister(reg_2.index, true);
		yyval.var.stored = reg_1.index;
	}
	yyval.var.index = -1;
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 21:
#line 221 "kompilator.y"
{
	unsigned long long int quickResult = quickMultiplication(yyvsp[-2].var, yyvsp[0].var);
	if (quickResult != -1) yyval.var.stored = quickResult;
	else {
		Register reg_1 = prepareRegister(yyvsp[-2].var);
		Register reg_2 = prepareRegister(yyvsp[0].var);
		Register reg_3 = getFreeRegister();
		addOutput("JODD "+intToString(reg_2.index)+" "+intToString(getK() + 5));
		addOutput("SHL "+intToString(reg_1.index));
		addOutput("SHR "+intToString(reg_2.index));
		addOutput("JZERO "+intToString(reg_2.index)+" "+intToString(getK() + 5));
		addOutput("JUMP "+intToString(getK() - 4));
		addOutput("ADD "+intToString(reg_3.index)+" "+intToString(reg_1.index));
		addOutput("DEC "+intToString(reg_2.index));
		addOutput("JUMP "+intToString(getK() - 6));
		freeRegister(reg_2.index, true);
		freeRegister(reg_1.index, true);
		yyval.var.index = -1;
		yyval.var.stored = reg_3.index;
		yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
	}
;
    break;}
case 22:
#line 243 "kompilator.y"
{
	if (false) {}
	else {
		Register reg1 = prepareRegister(yyvsp[-2].var);
		Register reg2 = prepareRegister(yyvsp[0].var);
		Register reg3 = getFreeRegister();
		addOutput("INC "+intToString(reg1.index));
		addOutput("SUB "+intToString(reg1.index)+" "+intToString(reg2.index));
		addOutput("JZERO "+intToString(reg1.index)+" "+intToString(getK() + 3));
		addOutput("INC "+intToString(reg3.index));
		addOutput("JUMP "+intToString(getK() - 3));
		freeRegister(reg1.index, true);
		freeRegister(reg1.index, true);
		yyval.var.stored = reg3.index;
	}
	yyval.var.index = -1;
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 23:
#line 261 "kompilator.y"
{
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	Register reg_3 = getFreeRegister();
	Register reg_4 = getFreeRegister();
	addOutput("JZERO "+intToString(reg_2.index)+" "+intToString(getK() + 14));
	addOutput("RESET "+intToString(reg_3.index));
	addOutput("RESET "+intToString(reg_4.index));
	addOutput("ADD "+intToString(reg_4.index)+" "+intToString(reg_2.index));
	addOutput("SUB "+intToString(reg_4.index)+" "+intToString(reg_1.index));
	addOutput("JZERO "+intToString(reg_4.index)+" "+intToString(getK() + 2));
	addOutput("JUMP "+intToString(getK() + 11));
	addOutput("ADD "+intToString(reg_3.index)+" "+intToString(reg_2.index));
	addOutput("ADD "+intToString(reg_4.index)+" "+intToString(reg_3.index));
	addOutput("SHL "+intToString(reg_4.index));
	addOutput("SUB "+intToString(reg_4.index)+" "+intToString(reg_1.index));
	addOutput("JZERO "+intToString(reg_4.index)+" "+intToString(getK() + 2));
	addOutput("JUMP "+intToString(getK() + 3));
	addOutput("SHL "+intToString(reg_3.index));
	addOutput("JUMP "+intToString(getK() - 6));
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_3.index));
	addOutput("JUMP "+intToString(getK() - 15));
	freeRegister(reg_2.index, true);
	freeRegister(reg_3.index, true);
	freeRegister(reg_4.index, true);
	yyval.var.index = -1;
	yyval.var.stored = reg_1.index;
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 24:
#line 294 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	Register reg_3 = getFreeRegister();
	addOutput("COPY "+intToString(reg_3.index)+" "+intToString(reg_2.index));
	addOutput("SUB "+intToString(reg_2.index)+" "+intToString(reg_1.index));
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_3.index));
	addOutput("ADD "+intToString(reg_1.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	freeRegister(reg_3.index, true);
	addOutput("JZERO "+intToString(reg_1.index)+" "+intToString(getK() + 2));
	setRegister(reg_1, true);
	st.push(getK());
	addOutput("JUMP ");
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 25:
#line 311 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	Register reg_3 = getFreeRegister();
	addOutput("COPY "+intToString(reg_3.index)+" "+intToString(reg_2.index));
	addOutput("SUB "+intToString(reg_2.index)+" "+intToString(reg_1.index));
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_3.index));
	addOutput("ADD "+intToString(reg_1.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	freeRegister(reg_3.index, true);
	setRegister(reg_1, true);
	st.push(getK());
	addOutput("JZERO "+intToString(reg_1.index)+" ");
	freeRegister(reg_1.index, true);
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 26:
#line 328 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	addOutput("SUB "+intToString(reg_2.index)+" "+intToString(reg_1.index));
	freeRegister(reg_1.index, true);
	reg_2.id = "";
	setRegister(reg_2, true);
	st.push(getK());
	addOutput("JZERO "+intToString(reg_2.index)+" ");
	freeRegister(reg_2.index, true);
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 27:
#line 341 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	reg_1.id = "";
	setRegister(reg_1, true);
	st.push(getK());
	addOutput("JZERO "+intToString(reg_1.index)+" ");
	freeRegister(reg_1.index, true);
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 28:
#line 354 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	addOutput("INC "+intToString(reg_2.index));
	addOutput("SUB "+intToString(reg_2.index)+" "+intToString(reg_1.index));
	freeRegister(reg_1.index, true);
	reg_2.id = ""; setRegister(reg_2, true);
	st.push(getK());
	addOutput("JZERO "+intToString(reg_2.index)+" ");
	freeRegister(reg_2.index, true);
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 29:
#line 367 "kompilator.y"
{
	st.push(getK());
	Register reg_1 = prepareRegister(yyvsp[-2].var);
	Register reg_2 = prepareRegister(yyvsp[0].var);
	addOutput("INC "+intToString(reg_1.index));
	addOutput("SUB "+intToString(reg_1.index)+" "+intToString(reg_2.index));
	freeRegister(reg_2.index, true);
	reg_1.id = ""; setRegister(reg_1, true);
	st.push(getK());
	addOutput("JZERO "+intToString(reg_1.index)+" ");
	freeRegister(reg_1.index, true);
	yyval.var.error = checkIfInitialized(yyvsp[-2].var, yyvsp[0].var);
;
    break;}
case 30:
#line 384 "kompilator.y"
{
	yyval.var.stored = addIterator(string(yyvsp[0].str));
	yyval.var.name = yyvsp[0].str;
	yyval.var.value = 0;
	yyval.var.index = -1;
;
    break;}
case 31:
#line 394 "kompilator.y"
{ yyval.var = yyvsp[0].var; ;
    break;}
case 32:
#line 395 "kompilator.y"
{/*
	Register reg = getFreeRegister();
	setValueInRegister($1, reg.index);
	$$.stored = reg.index;
	$$.value = $1;
	$$.name = strdup("");
	$$.index = -1;*/
	yyval.var.stored = -1;
	yyval.var.value = yyvsp[0].num;
	yyval.var.name = strdup("");
	yyval.var.index = -1;
;
    break;}
case 33:
#line 411 "kompilator.y"
{ yyval.var = yyvsp[0].var; ;
    break;}
case 34:
#line 412 "kompilator.y"
{
	yyval.var.value = yyvsp[0].num;
	yyval.var.name = strdup("");
	yyval.var.stored = storeTempVariable(yyvsp[0].num);
	yyval.var.index = -1;
;
    break;}
case 35:
#line 422 "kompilator.y"
{
	if (isDeclared(yyvsp[0].str, false)) {
		Variable v = getVariable(yyvsp[0].str);
		if (v.iterator) yyval.var = for_stack.top(); //We are taking most nested iterator of this ID
		else {
			yyval.var.stored = v.stored;
			yyval.var.value = v.value;
			yyval.var.name = yyvsp[0].str;
			yyval.var.index = -1;
		}
	}
	else yyerror("Variable "+string(yyvsp[0].str)+" not declared");
;
    break;}
case 36:
#line 435 "kompilator.y"
{
	if (isDeclared(yyvsp[-3].str, true)) {
		Variable v = getVariable(yyvsp[-3].str);
		if (yyvsp[-1].num >= 0 && yyvsp[-1].num < v.length) {
			yyval.var.stored = v.stored + yyvsp[-1].num;
			yyval.var.value = 0;
			yyval.var.name = yyvsp[-3].str;
			yyval.var.index = -1;
		}	else yyerror("In array "+string(yyvsp[-3].str)+" index out of bounds: "+intToString(yyvsp[-1].num));
	} else yyerror("Array "+string(yyvsp[-3].str)+" not declared");
;
    break;}
case 37:
#line 446 "kompilator.y"
{
	if (isDeclared(yyvsp[-3].str, true)) {
		if (isDeclared(yyvsp[-1].str, false)) {
			Variable v = getVariable(yyvsp[-3].str);
			Variable v_2 = getVariable(yyvsp[-1].str);
			yyval.var.stored = v.stored;
			yyval.var.index = v_2.stored;
			yyval.var.value = 0;
			yyval.var.name = yyvsp[-3].str;
		} else yyerror("Variable "+string(yyvsp[-1].str)+" not declared");
	} else yyerror("Array "+string(yyvsp[-3].str)+" not declared");
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 460 "kompilator.y"



/* Main function */
int main(int argc, char* argv[]) {
	int flag = 1;
	if (argc > 1) flag = atoi(argv[1]);
	setPrintFlag(flag);

	return yyparse();
}
